#!/bin/bash

NUM_TRIALS=50
NUM_NESTS=20
MAX_NUM_ANTS=2000
NUM_ANTS_STEP_SIZE=50
NUM_STEPS=$(($MAX_NUM_ANTS / $NUM_ANTS_STEP_SIZE))

for ((i=$NUM_ANTS_STEP_SIZE; i <= $MAX_NUM_ANTS; i+=$NUM_ANTS_STEP_SIZE))
do
    echo $i
    python run.py $NUM_TRIALS $i $NUM_NESTS Ant Nest &
done
